### ISSUE TITLE
Running Opentopodata on Github Codespaces

### ISSUE THREAD

**Issue by monkeybanana1024** [ajnisbet/opentopodata#102]
Hi, 
For a school project I wanted to get elevation data for an area. After finding out how clumsy and difficult things are with google elevation api, I found this lifesaving repo. I would like to ask if anyone has successfully hosted this api without setting it up on the cloud. Currently I am using python for some projects, and I would like to know if I can link this api directly to the program as a function. 

Thanks, 
Arnav

P.S
If there is a free alternative to google earth engine that can provide satellite images, that would be awesome (please provide link)

**Comment by ajnisbet** [comment]
There are some instructions here for running the opentopodata server without docker, though they might be a bit old now: https://www.opentopodata.org/notes/running-without-docker/

Generally the steps are

* Install a rasterio wheel
  * Rasterio is critical to opentopodata
  * Rasterio is a huge thing to try build from source, if `pip install rasterio` starts building instead of downloading, try some different rasterio/python versions 
* The remaining dependencies should easily install with `pip install -r requirements.txt`
  * If that fails, try `pip install -r requirements.in`
* Run with `FLASK_APP=opentopodata/api.py DISABLE_MEMCACHE=1 flask run --port 5000`

All of this should work on windows, though no doubt with more difficulty. I don't have a windows machine to test on sorry.


---

Because opentopodata isn't a library, it doesn't have a setup.py file, and so can't be installed with pip.

You could copy `backend.py`, `utils.py`, and `config.py` into your project and import them! Or concatenate them all into an `opentopodata.py` file.

---

But if you just want to read locations by lat/lon from the 10m NED dataset, the simplest way might be

* Using GDAL, build a single-file index of the entire datasets
  * For gdal 3.9+ use `gdaltindex` to make a fast `GTI` index
    * `gdaltindex -recursive -filename_filter "*.tif" -f GPKG  ned10.gti.gpkg ./ned10/
  * For older gdal versions you're stuck with `gdalbuildvrt`
* Then copy/paste the `_get_elevation_from_path` from `backend.py` and you should be good to go, using the gti/vrt path  from the previous step.
