### ISSUE TITLE
Unrealistic elevation data from Mapzen

### ISSUE THREAD

**Issue by magma1447** [ajnisbet/opentopodata#11]
I assume this is an issue with the Mapzen data, and maybe I should raise a ticket there. But I wanted to first double check that I am understanding that part correctly.

When fetching the elevation with https://api.opentopodata.org/v1/mapzen?locations=42.351033,-71.0508 I am getting 8112 meters as a response. This is in the middle of Boston, and 0-50 meters seems more realistic.

Should I ask them if there is something bogus in that area?

**Comment by magma1447** [comment]
I have actually found quite a few places. I guess the data wasn't as reliable as I expected. If you feel there is nothing to follow up on, feel free to just close this issue.

**Comment by ajnisbet** [comment]
Here's a colour render of the Mapzen elevation around Boston, darker purple means higher elevation
![image](https://user-images.githubusercontent.com/10361305/92341394-6a628180-f072-11ea-88a7-f37357c28592.png)

There are some very large values along the waterfront, probably from where a bathymetry dataset was merged with the land.

The corruption is present in the raw elevation from Mapzen - I double checked to make sure I didn't mess anything up when I downloaded it for api.opentopodata.org . The processed tile formats offered by Mapzen don't have the corruption around Boston, perhaps because they are averaged and at a lower resolution. 

So yeah this is an issue Mapzen would need to solve. For now you could use NED or SRTM as your dataset. Or in opentopodata you could query say a 3x3 grid of points spaced ~30m apart and take the median, as the corruption seems to be pretty localised.

And thanks for raising the issue! I'll keep an eye out for other Mapzen data quality issues, it might be worth adding one of the processed formats as a source.
