### ISSUE TITLE
ned10m renamed not recognized as a supported file format

### ISSUE THREAD

**Issue by allenyhu** [ajnisbet/opentopodata#12]
Hi, I'm trying to run a local server of the ned10m dataset. I've followed the instructions here: https://www.opentopodata.org/datasets/ned/. When I hit the server, I see this error:

`ERROR in api: 'data/ned10m/USGS_13_n37w120_renamed.tif' not recognized as a supported file format.`

Not sure if the SRTM file renaming script has a bug or if I downloaded the files wrong.

**Comment by ajnisbet** [comment]
Did you resolve this? It should be fixed in recent releases.

**Comment by allenyhu** [comment]
Sorry, I did resolve this. Turns out the way I was pulling the files wasn't correct. If you want, I can make a PR for a download script and list of filenames like you have for the SRTM data

**Comment by ajnisbet** [comment]
Ok great, glad it's working!

I didn't include a list of URLs for the NED dataset because it's still being updated, and I didn't want the list to become out of date and incomplete. 

But if you have a script that can generate a list of urls or scrape the listing to download the files, I'd link to it or accept a PR if you like!
