### ISSUE TITLE
What is the source of "test-dataset" api

### ISSUE THREAD

**Issue by mttucl** [ajnisbet/opentopodata#63]
I'm getting different bathymetry values from below data sources. I can't find the source for the "test-dataset". Is it from an open source dataset?

[test-dataset](https://api.opentopodata.org/v1/test-dataset?locations=13,-17.1)

[mapzen](https://api.opentopodata.org/v1/mapzen?locations=13,-17.1)

[etopo1](https://api.opentopodata.org/v1/etopo1?locations=13,-17.1)

[gebco2020](https://api.opentopodata.org/v1/gebco2020?locations=13,-17.1)

**Comment by ajnisbet** [comment]
Yes, test-dataset is etopo1 downsampled to roughly 100m. It is very low resolution because it is included in the source code, and I want to keep that small.

It's mostly used for testing, maybe it's enough to check if your lat/lon numbers are the right way around. But yeah it wont agree with the other datasets very closely, when 50km of the coast like in your example.

You get closer elevation results in flatter areas like the Australian outback

https://api.opentopodata.org/v1/test-dataset?locations=-28.071295883338827,%20131.48040446972746

https://api.opentopodata.org/v1/mapzen?locations=-28.071295883338827,%20131.48040446972746

Thanks for raising this though, I'll look at documenting this better.
