### ISSUE TITLE
How to get altitude from lat and long in local?

### ISSUE THREAD

**Issue by madenburak** [ajnisbet/opentopodata#76]
I want to lat, long and altitude values in a table or text. How I access this data? I tried local installation without docker but I got error at `api.py`. Which method should I follow?

**Comment by ajnisbet** [comment]
I highly recommend running in docker if possible: it solves a lot of issues with difficult geospatial dependencies.

Otherwise here are the instructions to follow: https://www.opentopodata.org/notes/running-without-docker/

To help you more please share

* Which version of opentopodata you are using (or when you downloaded it)
* What operating system you are using (eg Windows 10)
* What you tried (ideally the exact commands you used)
* What error you are getting (paste the output or a screenshot)

**Comment by madenburak** [comment]
- opentopodata 1.8.3
- Ubuntu
- I tried minimal installation in running-without-docker. I used this command `FLASK_APP=opentopodata/api.py DISABLE_MEMCACHE=1 flask run --port 5000` after installation steps.
- I got this output: 
```
 * Serving Flask app "opentopodata/api.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

- When I clicked the link, It gave error to me.
`{"error":"No dataset name provided. Try a url like '/v1/test-dataset?locations=-10,120' to get started, and see https://www.opentopodata.org for full documentation.","status":"INVALID_REQUEST"}`

**Comment by ajnisbet** [comment]
Thanks for this info!

opentopodata is software for turning an elevation dataset into an API. As well as running the software, you'll need to supply an elevation dataset: there are instructions under the "Datasets" tab for how to download and install some common elevation datasets: https://www.opentopodata.org/ if you're not sure which dataset you need to use, the mapzen one is a good start.

If you just need small amounts of data, I also host a free public api at api.opentopodata.org
