### ISSUE TITLE
Unsupported filetype

### ISSUE THREAD

**Issue by MegaS67** [ajnisbet/opentopodata#80]
When i try to start the server with a included eu-dem TIF from Copernicus i get:

`Invalid config: Unsupported filetype for  'data/eudem/N3000000E4000000.TIF'.`

No problem with the Test TIF in test-eu-dem-subset

**Comment by ajnisbet** [comment]
Hmm, this could be related to the recent Docker image decay. That problem is fixed on the latest `dev` branch: could you try running `git checkout dev; git pull; make build` then trying again?

You could also try the alternate docker image: `make build-m1`. Despite the name, it works on non-M1 architectures.

**Comment by MegaS67** [comment]
I have been able to solve the problem. The error was that I used a shared folder to exchange the tif file between Windows and the Linux VM. The tif file was downloaded with Windows and copied into the Linux exchange folder. For whatever reason Linux then reports the data type error. Downloading with Linux was the solutionl
