### ISSUE TITLE
mapzen: make run error

### ISSUE THREAD

**Issue by viacheslavspasibo** [ajnisbet/opentopodata#82]
Hi There, 

I changed the dataset from the test one to mapzen. 

I extracted all the files and now I have the following data:
data/mapzen/
N00
N01
...
each folder has N00E000.tif  N00E024.tif and so on 
When I run make run  then I get an error:
ERROR:root:Invalid config: SRTM-type tile coords must be unique, cannot be the same tile with different extensions.
ERROR:root:Uncaught exception while trying to pre-populate the cache. This probably means that Open Topo Data isn't working.

Which format should be the mapzen files at the end?

**Comment by ajnisbet** [comment]
Sorry for the delay in getting back to you!

The filename `N00E024.tif` is fine!

What sometimes happens is temporary/other files get created like `N00E024.pdf` or `N00E024.tmp`. This can be due to transfer errors for example.

Now when opentopodata needs to look up the file `N00E024` it doesn't know whether to read `N00E024.tif` or `N00E024.pdf`.

The challenge is finding this unnecessary file, and I admit opentopodata isn't very helpful here.

You could use a command like

```bash
find . -not -name "*.tif"
```

Let me know if this helps, and if so, what file extension caused the issue.  Because this is a common issue, I have a list of extensions that opentopodata will ignore (for example `.tmp`).
