### ISSUE TITLE
Issue accessing dataset mounted from s3 bucket

### ISSUE THREAD

**Issue by virajprakash** [ajnisbet/opentopodata#88]
Hi, I am getting the following error when I use 'make run'
ERROR:root:Invalid config: No dataset folder found at location 'data/dataset'
However, I already made sure that the S3 bucket is setup correctly using s3fs and verified on my local file system
s3fs idemo /root/opentopodata/data -o passwd_file=${HOME}/.passwd-s3fs

<img width="536" alt="Screen Shot 2023-12-01 at 6 34 13 PM" src="https://github.com/ajnisbet/opentopodata/assets/27041287/29b97c71-6bbe-4603-b3f7-6c70f994053f">
Also attached are relevant portions of my config.yaml and makefile.

Makefile portion

run: 
	docker run --rm -it --volume /root/opentopodata/data:/app/data:ro -p 5000:5000 opentopodata:$(VERSION) 

config.yaml:

- name: ned10m
  path: data/dataset

Thanks in advance !!!

Yes I know it is not recommended to use root and I will be sure to change that but I am almost positive this is a separate issue.

**Comment by ajnisbet** [comment]
Hmmm, thanks for the thorough explanation! I haven't encountered this before but I can suggest some things to try:

One would be mounting one directory deeper, so you're passing a "normal" directory to docker rather than a mount point. So mounting `s3fs idemo /root/opentopodata/data/s3mount/` then  the config file would point to `data/s3mount/dataset`.

The next step would be execing into the running docker container and having a look around.

* Run the container with the `docker run` command above
* In a new terminal run `docker ps` to get the container ID for opentopodata
* Run `docker exec -it XXXXX bash` where XXXX is the container ID
* `cd /app/`
* `ls -lh` and make sure the `data` folder is there with normal permissions
* `ls -lh /app/data/` and make sure the `dataset` folder is there with normal permissions
* `ls -lgh /app/data/dataset/` and make sure the tifs are there.

**Comment by ajnisbet** [comment]
I've never used s3fs, but have used [rclone mount](https://rclone.org/commands/rclone_mount/) to mount cloud buckets then have those as docker volumes for opentopodata and gpxz: you could look into that if you're having lots of issues.

**Comment by virajprakash** [comment]
I have also experimented with multiple config paths including the one you suggested and I also did make build before testing any of them using make run. However I am still seeing 'no dataset folder' when i try to run

**Comment by virajprakash** [comment]
We also tried using s3fs and no luck with that unfortunately

**Comment by ajnisbet** [comment]
It looks like the files are at `data/dataset` rather than `data/s3mount/dataset`, could you try updating `config.yaml` to match?

You could also try an absolute path: `/app/data/dataset`

**Comment by ajnisbet** [comment]
> It looks like the files are at `data/dataset` rather than `data/s3mount/dataset`, could you try updating `config.yaml` to match?
> 
> You could also try an absolute path: `/app/data/dataset`

Closing assuming this was the issue.
