### ISSUE TITLE
Calculating value for filename_tile_size

### ISSUE THREAD

**Issue by tombarton** [ajnisbet/opentopodata#92]
Probably an incredibly stupid question but how does one go about calculating the `filename_tile_size` value? I'm trying to implement a dataset for Northern Ireland. I've tiled my data so filenames follow the appropriate convention, but I can't get my head around the tile size value? I realise they're supposed to covered degrees of coverage rather than meters. Any advice would be much appreciated!

**Comment by ajnisbet** [comment]
`filename_tile_size` is in the units of whatever `filename_epsg` is set to. `filename_epsg` would typically be set to the projection of the dataset.




By default, `filename_epsg` is [4326](https://epsg.io/4326) which is the code for lat/lon projection, so `filename_tile_size` is in units of degrees. But you can change this!

For example, if the projection of your dataset is [TM75 / Irish Grid](https://epsg.io/29903), that projection is in metres, so your tile size would be in metres. If your tiles were of size 2000 x 2000, at a 10m resolution, then you would use

```yaml
filename_epsg: 29903  # Corresponds to TM75 / Irish Grid
filename_tile_size: 20000  # Size of tile, in metres.
```

If you have access to gdal tools you can run `gdalinfo your_file.tif` to see what the resolution, size, projection, and bounding coordinates are. If you can't figure out the settings, please share the output of the `gdalinfo` command here (or link to the file) and I can help with the exact settings needed.

--- 

That said, if you're using the [OSNI 10m DTM](https://www.nidirect.gov.uk/articles/10m-digital-terrain-model-height-data) then unfortunately it's not going to be possible to do this: opentopodata needs square tiles to do the filename coordinates trick, and these tiles are 209 x 640.

So you would need do re-tile the data files: splitting them up into even squares.

Instead, because that full dataset is only 300 files, I'd suggest to use [gdalwarp](https://gdal.org/programs/gdalwarp.html) to merge them all into a single tile (which opentopodata will easily handle!) or make them into a VRT like this: https://www.opentopodata.org/datasets/eudem/#adding-eu-dem-to-open-topo-data

---

I would like to handle arbitrary datasets without having to rename a bunch of files (https://github.com/ajnisbet/opentopodata/issues/91) but haven't got round to it yet :( 

Let me know how you get on!

**Comment by tombarton** [comment]
That is amazing, thank you both so much.

@ajnisbet that is exactly what I ended up doing with the NI dataset and it worked a treat.
