### ISSUE TITLE
Question: Mount config on docker run

### ISSUE THREAD

**Issue by arnesetzer** [ajnisbet/opentopodata#99]
Is there a specific reason why the config.yaml is "baked in" into the docker image, but the data is not? Since `make run` loads the datasets dynamically, I was wondering why the config file is, more or less, static.

Building on the question: What's your opinion on a PR which makes it possible to load the config.yaml dynamically as the data?

**Comment by ajnisbet** [comment]
Good idea!

Because opentopodata uses caching both in memcached and in the python process's memory between requests, the safest thing to do would be to kill both uwsgi (which manages python) and memcached like this:

* A new service in `docker/supervisord.conf` that watches for changes in `config.yaml` and `example-config.yaml` using something like [watchdog](https://github.com/gorakhargosh/watchdog)
* If the config file has changed:
  * Gracefully stop uwsgi
  * Wipe memcached
  * Start uwsgi (which will pull in the new config)
  * Run the `warm_cache` service

This is basically the same as what `make build; make run` would do. But at least you don't have to trigger it manually.

It would be nicer in theory to do something like only reloading the datasets that were changed in the config instead of nuking everything. This would speed up reloads! But I fear that the selective cache invalidation of that approach would be threaten the reliability of the software.

**Comment by ajnisbet** [comment]
Fixed in https://github.com/ajnisbet/opentopodata/commit/d1fc1a733a097b2fbd5dd39336c29a15fb8f0840
